-- Chapter 6: working with strings
-- SQL is not designed to perform complex string manipulations. Use another language such as Python for string manipulation.
-- If you are interested, feel free to check out SQL Cookbook for string manipulation examples.
